# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasertApp', '0002_serivces_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serivces',
            options={'managed': True, 'ordering': ['-created_date'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='serivces',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
