# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasertApp', '0003_auto_20170324_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serivces',
            name='logo',
        ),
        migrations.AddField(
            model_name='serivces',
            name='icon',
            field=models.CharField(default='', help_text='Please user this website to grap your icon <a href="https://material.io/icons/" target="_blank">Icons</a>', max_length=150),
            preserve_default=False,
        ),
    ]
