# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasertApp', '0004_auto_20170324_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='serivces',
            name='service_name_en',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutions',
            name='name_en',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
