# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasertApp', '0006_auto_20170324_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutioncategory',
            old_name='category_name',
            new_name='category_name_ar',
        ),
        migrations.AddField(
            model_name='solutioncategory',
            name='category_name_en',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
