# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lasertApp', '0007_auto_20170324_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='serivces',
            name='logo',
            field=models.ImageField(default='', upload_to=b'service/'),
            preserve_default=False,
        ),
    ]
